version: '{build}'

image: Visual Studio 2017

configuration: Release

assembly_info:
  patch: false

before_build:
- cmd: dotnet restore

build:
  project: UltimateTeam.Toolkit.sln

after_build:
  - cmd: dotnet pack UltimateTeam.Toolkit\UltimateTeam.Toolkit.csproj --include-symbols
  # - cmd: appveyor PushArtifact "UltimateTeam.Toolkit.%GitVersion_NuGetVersion%.nupkg"
  # - cmd: appveyor PushArtifact "UltimateTeam.Toolkit.%GitVersion_NuGetVersion%.symbols.nupkg"